### ISSUE TITLE
le blog-contact en .po est en français !!

### ISSUE THREAD

**Issue by Chrisaiki** [duniter/blog-posts#49]
Le en .po est en français alors que le.md est en anglais !!!

**Comment by c-geek** [comment]
Pas d'affolement, tout est normal ! Lorsque l'on rédige un article il est dans une langue d'origine, puis cela génère 2 .po : un FR et un EN.

Ainsi pour un article rédigé initialement en français il y aura :
- un .po pour la traduction française (non traduite)
- un .po pour la traduction anglaise (à traduire)
