### ISSUE TITLE
http://fr.duniter.org/presentation/ : petites modifs

### ISSUE THREAD

**Issue by Cywil23** [duniter/blog-posts#85]
Bonjour,

Concernant ce fichier : https://github.com/duniter/blog-posts/blob/master/posts/2015-08-11-presentation.fr_FR.po

L.40 : "Bicoin" => "Bitcoin"

L.197 : "le membre doivent" => "les membres doivent" ou "le membre doit"

L.217 : "a lien" => "un lien"

L.236 : "les liens ne peuvent pas être écris" => "les liens ne peuvent pas être écrits"

Bon courage pour la suite du projet !! ;-)

**Comment by c-geek** [comment]
Si tu sais faire une pull request et que tu veux bien la réaliser, nous apprécierions fortement :-)

A noter que tu peux aussi passer directement par notre outil de traduction : https://weblate.duniter.org/ Il suffit alors de s'inscrire et modifier la traduction.

Dans tous les cas, dès que la modif est acceptée, ça met à jour directement le blog !

**Comment by Cywil23** [comment]
ok, je vais tenter d'aller plus loin dans ce sens.

Par contre, en suivant le lien https://weblate.duniter.org/ il est indiqué de suivre le lien http://vit.free.fr/yeswiki/wakka.php?wiki=TRM
Et sur cette page, il faudrait changer le lien vers https://weblate.duniter.org/ qui ne fonctionne pas (j'ai l'impression qu'il manque les ":" après le http...)

**Comment by c-geek** [comment]
Tu n'es pas obligé de suivre ce lien, c'est pour ceux traduisant la [Théorie Relative de la Monnaie](http://trm.creationmonetaire.info/).

Mais merci d'avoir relevé le lien cassé !
